"""Phase 1C multimodal intake endpoint.

Stateless: nothing about the request or response is persisted, cached, or
sent to any external service. No speech-to-text, text-to-speech, vision
analysis, LLM call, specialty inference, or media fetch happens here —
this endpoint only validates, normalizes, and evaluates a deterministic
state. See docs/architecture.md's Phase 1D notes for what comes after
this contract.
"""

import logging
import time

from fastapi import APIRouter

from app.schemas.multimodal_intake import MultimodalIntakeRequest, MultimodalIntakeResponse
from app.services.multimodal_intake_service import evaluate_intake

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post(
    "/intake/validate",
    summary="Validate and normalize a multimodal medical-navigation intake request",
    description=(
        "Accepts text symptoms, a main concern, duration, an optional location "
        "preference, an optional preferred-specialty slug, user-declared emergency "
        "indicators, a pre-generated voice transcript, and image/video URL "
        "**references**.\n\n"
        "- Image and video URLs are references only — this endpoint never "
        "fetches, opens, or analyzes the media they point to.\n"
        "- `voice_input.transcript` must already have been generated by the "
        "caller; this endpoint does not perform speech-to-text.\n"
        "- No media interpretation, LLM call, or specialty inference occurs in "
        "Phase 1C. This is a validation/normalization contract only.\n"
        "- This endpoint is non-diagnostic: it never returns a diagnosis, "
        "treatment advice, or a medical urgency score.\n"
        "- Emergency assistance is not provided through MedRoute AI. Emergency "
        "indicators are user-declared only, never inferred, and always take "
        "precedence: if declared, the response directs U.S. users to call 911."
    ),
)
async def validate_intake(payload: MultimodalIntakeRequest) -> MultimodalIntakeResponse:
    started = time.monotonic()
    response = evaluate_intake(payload)
    elapsed_ms = (time.monotonic() - started) * 1000

    # Safe operational metadata only: counts, booleans, and the generated
    # intake_id. Never symptoms, main_concern, transcripts, emergency-signal
    # values, or media URLs.
    logger.info(
        "intake_validated intake_id=%s status=%s text_received=%s voice_received=%s "
        "vision_received=%s symptom_count=%d image_count=%d video_count=%d "
        "duration_supplied=%s location_supplied=%s processing_ms=%.2f",
        response.intake_id,
        response.status.value,
        response.multimodal_status.text_received,
        response.multimodal_status.voice_received,
        response.multimodal_status.vision_received,
        len(payload.symptoms),
        response.multimodal_status.image_count,
        response.multimodal_status.video_count,
        payload.duration is not None,
        payload.location is not None,
        elapsed_ms,
    )

    return response
