"""Phase 2B/2C/2D: typed LangGraph conversation state for MedRoute AI's
multi-agent navigation graph (supervisor_router -> conversation_agent |
vision_agent -> medical_intake_agent -> safety_gate -> clarification ->
specialty_routing_agent -> provider_search_agent -> response_agent ->
text_to_speech).

All fields are JSON-serializable (plain dicts/lists/strings, never raw
pydantic model instances, SQLAlchemy rows, or raw media bytes) so the
state round-trips cleanly through LangGraph's checkpointer for pause/
resume across separate HTTP requests. Nothing beyond this typed shape —
no chain-of-thought, no raw model prompt, no uploaded media itself — is
ever persisted or returned to a caller. Raw media bytes are passed
transiently via a node's `config["configurable"]` (see
app/graph/nodes.py's vision_agent_node) and never enter this state; only
the small, already schema-validated VisionObservation dicts below do.

Fields below fall into two groups:

- Domain fields (Phase 1B-2C): the actual intake/routing/provider/response
  data every agent reads and writes — unchanged in shape and meaning from
  earlier phases.
- Orchestration fields (Phase 2D): explicit, inspectable multi-agent
  routing state — which agent is/was active, what was decided and why,
  and a running trace of which agents this turn actually visited. These
  exist so routing decisions are structured data, not implicit control
  flow, and so tests can assert on the exact agent path a turn took.
"""

import operator
from typing import Annotated, Any, TypedDict


class ConversationState(TypedDict, total=False):
    """LangGraph state for one MedRoute AI conversation thread."""

    # --- domain fields (Phase 1B-2C) ----------------------------------

    # The Phase 1C intake request, as a JSON-serializable dict
    # (MultimodalIntakeRequest.model_dump(mode="json")). Updated in place
    # only by the clarification node merging a confirmed answer — a
    # confirmed voice_input.transcript, once set, is never cleared or
    # rewritten by any node.
    intake_request: dict[str, Any]

    # Whether the caller wants a synthesized-speech response this turn.
    # Mirrored into speech_requested (see below) for the orchestration
    # state's naming convention; both are always kept equal.
    generate_speech: bool

    # Phase 2C: set directly in the initial state by the caller (never
    # derived by a node) when this turn's config["configurable"]["media"]
    # carries a validated upload — used only by supervisor_router_node to
    # decide whether to route to vision_agent at all. Never set on a
    # resumed clarification turn, so vision analysis only ever runs once
    # per turn.
    media_pending: bool

    # Phase 1C intake evaluation (MultimodalIntakeResponse.model_dump()).
    intake_response: dict[str, Any] | None
    missing_fields: list[str]

    # Set only by safety_gate; never derived from transcript/text content.
    is_emergency: bool

    # Set only by clarification, to choose its own outgoing conditional
    # edge after an interrupt/resume round-trip.
    just_resumed_clarification: bool

    # Phase 1D specialty routing (SpecialtyRoutingOut-shaped dict) and
    # Phase 1B provider search (ProviderSearchResponse-shaped dict).
    routing: dict[str, Any] | None
    provider_search: dict[str, Any] | None
    media_note: str | None

    # Phase 2B: the final safe, non-diagnostic response text and its
    # optional synthesized speech (AudioOutput-shaped dict).
    response_text: str | None
    audio: dict[str, Any] | None

    # Phase 2C: controlled, non-diagnostic visual observations (each a
    # JSON dict already validated against app.schemas.vision.
    # VisionObservation) from a directly-uploaded image or sampled video
    # frames — never fabricated, and never derived from a URL reference
    # (see MEDIA_UNAVAILABLE_NOTE / media_note above, which is unrelated
    # and still covers the separate, still-unimplemented vision_inputs-URL
    # path). Always empty when no media was uploaded this turn.
    vision_observations: list[dict[str, Any]]
    # A short, safe status note describing what happened during media
    # analysis (processed, no findings, or a safe failure/limitation
    # note) — never a fabricated description of a successful analysis
    # that didn't happen.
    media_analysis_note: str | None

    # --- orchestration fields (Phase 2D: multi-agent routing) ---------

    # The thread this turn belongs to, and a fresh identifier for this
    # specific turn within it (set once by the caller before the graph
    # ever runs; never regenerated by a node).
    thread_id: str
    turn_id: str

    # The raw, caller-supplied text this turn is about — the same
    # flattened symptoms/main_concern/confirmed-voice-transcript string
    # app.services.intent_classification_service.concern_text produces.
    # Never vision-derived, and never used for routing decisions beyond
    # supervisor_router's own intent classification.
    current_input: str | None
    # "voice" | "text" | "vision" | "clarification_resume" — a caller-
    # supplied signal (never inferred from content) describing which
    # channel produced current_input, set once per turn.
    input_modality: str

    # supervisor_router's structured classification of this turn — one of
    # ConversationIntent's values ("greeting", "medical_concern",
    # "clarification_answer", "unsupported_or_unclear"). Never overridden
    # by any later agent.
    detected_intent: str
    # The agent node currently/most-recently executing, and the one
    # supervisor_router decided should run next — explicit routing state
    # rather than implicit control flow, so a turn's path is inspectable
    # from the final state alone.
    active_agent: str | None
    next_agent: str | None
    # One entry per agent this turn actually visited, in order — e.g.
    # {"agent": "supervisor_router", "intent": "greeting"}. Accumulates
    # via the list-concatenation reducer (each node only ever *appends*
    # its own entry, never rewrites history) so the full path survives to
    # the final state even though most other fields are last-write-wins.
    conversation_history: Annotated[list[dict[str, Any]], operator.add]

    # "none" | "awaiting" | "resumed" — mirrors missing_fields/
    # just_resumed_clarification as an explicit, named status for the
    # orchestration layer.
    clarification_status: str

    # Denormalized, orchestration-facing mirrors of the domain fields
    # above — set by the same node that sets the domain field, always
    # kept equal to it. They exist so the multi-agent state has direct,
    # self-describing field names (selected_specialty, not
    # routing["specialty_slug"]) without requiring every consumer to know
    # the domain schema's nesting.
    normalized_intake: dict[str, Any] | None
    selected_specialty: str | None
    provider_results: dict[str, Any] | None
    speech_requested: bool
    audio_result: dict[str, Any] | None

    # Turn fingerprints (see api_client.build_voice_turn_fingerprint on
    # the Streamlit side, and ConversationRequest.turn_fingerprint) this
    # thread has already fully processed — checked by
    # conversation_service.run_conversation_turn *before* invoking the
    # graph at all, so a duplicate submission (e.g. a network retry, or a
    # server restarted-mid-flight client) returns the already-computed
    # response instead of re-running specialty routing, provider search,
    # or TTS. Accumulates via the same list-concatenation reducer as
    # conversation_history.
    processed_fingerprints: Annotated[list[str], operator.add]

    # Safe, non-diagnostic operational error notes (e.g. "vision provider
    # unavailable") an agent may want to surface for observability —
    # never a stack trace, prompt, or raw exception message. Accumulates
    # via the same reducer; empty for the overwhelming majority of turns.
    errors: Annotated[list[str], operator.add]

    # --- Phase 3A: extensible per-complaint clinical-context intake ----

    # The matched app.services.clinical_intake_service.ClinicalProtocol's
    # name, or None when the current concern matches no known protocol —
    # in which case clinical_intake_agent_node is a complete no-op and
    # every field below stays unset, preserving prior behavior exactly.
    clinical_protocol: str | None
    # A ClinicalContext-shaped dict (see app.schemas.clinical_context),
    # accumulated one answered protocol question at a time across
    # successive interrupt/resume round-trips on this same thread.
    clinical_context: dict[str, Any] | None
    # Set only by clinical_intake_agent_node, to choose its own outgoing
    # conditional edge after an interrupt/resume round-trip — mirrors
    # just_resumed_clarification's role for the existing clarification node.
    clinical_just_resumed: bool
    # "clinical_intake_agent" (loop for the next missing question) |
    # "red_flag_gate" (the red-flag question was just answered) |
    # "specialty_routing" (protocol complete) — read by
    # route_after_clinical_intake immediately after clinical_intake_agent_node
    # returns, never persisted beyond that one routing decision.
    clinical_next_step: str
    # Whether clinical_red_flag_gate_node found at least one explicitly
    # affirmed red flag this turn (see app.safety.red_flag_rules) — when
    # True, is_emergency is also set True so the existing emergency
    # response path (response_agent/compose_response) handles it exactly
    # like a user-declared emergency, without duplicating that logic.
    clinical_red_flag_affirmed: bool
    # A ClinicalNavigationSummary-shaped dict (see
    # app.schemas.clinical_context), set once the matched protocol's
    # questions are all answered and no red flag was affirmed. Always None
    # for a concern that matches no protocol, or one still in progress.
    clinical_navigation: dict[str, Any] | None
